grids = {
    "logistic_regression_base" : {'C': [0.03726121757536122], 'class_weight': [None], 'dual': [False], 'fit_intercept': [True], 'intercept_scaling': [1], 'l1_ratio': [None], 'max_iter': [100], 'multi_class': ['auto'],'n_jobs': [None],'penalty': ['l2'],'random_state': [48],'solver': ['lbfgs'],'tol': [0.0001],'verbose': [0],'warm_start': [False]},
	
	"logistic_regression_good" : {'C': [0.03134497205091213], 'class_weight': [None], 'dual': [False], 'fit_intercept': [True], 'intercept_scaling': [1], 'l1_ratio': [None], 'max_iter': [100], 'multi_class': ['auto'], 'n_jobs': [None], 'penalty': ['l2'], 'random_state': [48], 'solver': ['lbfgs'], 'tol': [0.0001], 'verbose': [0], 'warm_start': [False]},
	
	"random_forest_good" : {'bootstrap': [True], 'ccp_alpha': [0.0], 'class_weight': [None], 'criterion': ['gini'], 'max_depth': [11], 'max_features': ['sqrt'], 'max_leaf_nodes': [None], 'max_samples': [None], 'min_impurity_decrease': [0.0], 'min_samples_leaf': [235], 'min_samples_split': [2], 'min_weight_fraction_leaf': [0.0], 'n_estimators': [100], 'n_jobs': [None], 'oob_score': [False], 'random_state': [48], 'verbose': [0], 'warm_start': [False]},
	
	"xgboost_good" : {'objective': ['binary:logistic'], 'use_label_encoder': [False], 'base_score': [0.5], 'booster': ['gbtree'], 'callbacks': [None], 'colsample_bylevel': [1], 'colsample_bynode': [1], 'colsample_bytree': [1], 'early_stopping_rounds': [10], 'enable_categorical': [False], 'eval_metric': ['auc'], 'gamma': [0.0008166591830054634], 'gpu_id': [-1], 'grow_policy': ['depthwise'], 'importance_type': [None], 'interaction_constraints': [''], 'learning_rate': [0.11264611], 'max_bin': [256], 'max_cat_to_onehot': [4], 'max_delta_step': [0], 'max_depth': [4], 'max_leaves': [232], 'min_child_weight': [31], 'monotone_constraints': ['()'], 'n_estimators': [10000], 'n_jobs': [0], 'num_parallel_tree': [1], 'predictor': ['auto'], 'random_state': [48], 'reg_alpha': [0.886654437], 'reg_lambda': [1.82229924], 'sampling_method': ['uniform'], 'scale_pos_weight': [1], 'subsample': [1], 'tree_method': ['hist'], 'validate_parameters': [1], 'verbosity': [None], 'class_weight': [None], 'eta': [0.11264610667248227], 'lambda': [1.822299189991579], 'alpha': [0.8866544502153582]},
	
	"lightgbm_good" : {'boosting_type': ['gbdt'], 'class_weight': [None], 'colsample_bytree': [0.8], 'importance_type': ['split'], 'learning_rate': [0.1], 'max_depth': [6], 'min_child_samples': [370], 'min_child_weight': [0.001], 'min_split_gain': [0.0], 'n_estimators': [10000], 'n_jobs': [1], 'num_leaves': [12], 'objective': [None], 'random_state': [48], 'reg_alpha': [1.7786201857096935e-08], 'reg_lambda': [0.0003320897385975011], 'silent': ['warn'], 'subsample': [0.9], 'subsample_for_bin': [200000], 'subsample_freq': [1], 'early_stopping_round': [10], 'first_metric_only': [True]},
	
	"logistic_regression_not_good" : {'C': [0.02436512422392614], 'class_weight': [None], 'dual': [False], 'fit_intercept': [True], 'intercept_scaling': [1], 'l1_ratio': [None], 'max_iter': [100], 'multi_class': ['auto'], 'n_jobs': [None], 'penalty': ['l2'], 'random_state': [48], 'solver': ['lbfgs'], 'tol': [0.0001], 'verbose': [0], 'warm_start': [False]},
	
	"random_forest_not_good" : {'bootstrap': [True], 'ccp_alpha': [0.0], 'class_weight': [None], 'criterion': ['gini'], 'max_depth': [12], 'max_features': ['sqrt'], 'max_leaf_nodes': [None], 'max_samples': [None], 'min_impurity_decrease': [0.0], 'min_samples_leaf': [65], 'min_samples_split': [2], 'min_weight_fraction_leaf': [0.0], 'n_estimators': [100], 'n_jobs': [None], 'oob_score': [False], 'random_state': [48], 'verbose': [0], 'warm_start': [False]},
	
	"xgboost_not_good" : {'objective': ['binary:logistic'], 'use_label_encoder': [False], 'base_score': [0.5], 'booster': ['gbtree'], 'callbacks': [None], 'colsample_bylevel': [1], 'colsample_bynode': [1], 'colsample_bytree': [1], 'early_stopping_rounds': [10], 'enable_categorical': [False], 'eval_metric': ['auc'], 'gamma': [0.01508876226882897], 'gpu_id': [-1], 'grow_policy': ['depthwise'], 'importance_type': [None], 'interaction_constraints': [''], 'learning_rate': [0.62638551], 'max_bin': [256], 'max_cat_to_onehot': [4], 'max_delta_step': [0], 'max_depth': [3], 'max_leaves': [202], 'min_child_weight': [116], 'monotone_constraints': ['()'], 'n_estimators': [10000], 'n_jobs': [0], 'num_parallel_tree': [1], 'predictor': ['auto'], 'random_state': [48], 'reg_alpha': [1.75941014], 'reg_lambda': [8.30757332], 'sampling_method': ['uniform'], 'scale_pos_weight': [1], 'subsample': [1], 'tree_method': ['hist'], 'validate_parameters': [1], 'verbosity': [None], 'class_weight': [None], 'eta': [0.6263855044263522], 'lambda': [8.307573462298937], 'alpha': [1.7594101338630361]},
	
	"lightgbm_not_good" : {'boosting_type': ['gbdt'], 'class_weight': [None], 'colsample_bytree': [0.9], 'importance_type': ['split'], 'learning_rate': [0.1], 'max_depth': [6], 'min_child_samples': [110], 'min_child_weight': [0.001], 'min_split_gain': [0.0], 'n_estimators': [10000], 'n_jobs': [1], 'num_leaves': [1012], 'objective': [None], 'random_state': [48], 'reg_alpha': [2.5991797296621045e-07], 'reg_lambda': [1.138797202430596], 'silent': ['warn'], 'subsample': [1.0], 'subsample_for_bin': [200000], 'subsample_freq': [1], 'early_stopping_round': [10], 'first_metric_only': [True]},
	
	"logistic_regression_meta" : {'C': [80.16389938139379], 'class_weight': [None], 'dual': [False], 'fit_intercept': [True], 'intercept_scaling': [1], 'l1_ratio': [None], 'max_iter': [100], 'multi_class': ['auto'], 'n_jobs': [None], 'penalty': ['l2'], 'random_state': [48], 'solver': ['lbfgs'], 'tol': [0.0001], 'verbose': [0], 'warm_start': [False]}
}